services:
  - type: web
    name: attendance-ml
    env: python
    plan: free
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()" -b 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URI
        value: "postgresql://neondb_owner:npg_qJ9KMC5WXlOy@ep-lingering-breeze-anqvztru.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require"
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
